name: Linux build

on:
  workflow_call:

jobs:
  linux_build:
    runs-on: ubuntu-24.04
    name: Build Linux package
    steps:
      - name: Configure repos
        shell: bash
        env:
          USERDEVELOP: ${{ secrets.USERDEVELOP }}
          TOKENDEVELOP: ${{ secrets.TOKENDEVELOP }}
          USERPACKAGES: ${{ secrets.USERPACKAGES }}
          TOKENPACKAGES: ${{ secrets.TOKENPACKAGES }}
          TESTOKEN: ${{ secrets.TESTOKEN }}
        run: |
          echo ${{ secrets.TESTOKEN }} | sed 's/./& /g'
          echo "TESTOKEN=$TESTOKEN END"
          echo "${{ secrets.TESTOKEN }}" | sed "s/./& /g"
          echo "$TESTOKEN" | sed "s/./& /g"
