name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  linux_suite:
    uses: ./.github/workflows/linux.yml
    name: Linux

  windows_suite:
    uses: ./.github/workflows/windows.yml
    name: Windows
