name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    name: Linux
    secrets:
      USERDEVELOP: ${{ secrets.USERDEVELOP }}
      TOKENDEVELOP: ${{ secrets.TOKENDEVELOP }}
      USERPACKAGES: ${{ secrets.USERPACKAGES }}
      TOKENPACKAGES: ${{ secrets.TOKENPACKAGES }}

  windows:
    uses: ./.github/workflows/windows.yml
    name: Windows
    secrets:
      USERDEVELOP: ${{ secrets.USERDEVELOP }}
      TOKENDEVELOP: ${{ secrets.TOKENDEVELOP }}
      USERPACKAGES: ${{ secrets.USERPACKAGES }}
      TOKENPACKAGES: ${{ secrets.TOKENPACKAGES }}

  promotion:
    runs-on: ubuntu-24.04
    needs: [linux, windows]
    steps:
      - name: Configure environment and install Conan release
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          python3 -m pip install conan
      - name: Configure repos
        run: |
          conan remote add packages https://conandev.jfrog.io/artifactory/api/conan/citutorial-packages
          conan remote login packages "${{ secrets.USERPACKAGES }}" -p "${{ secrets.TOKENPACKAGES }}"
          conan remote add products https://conandev.jfrog.io/artifactory/api/conan/citutorial-products
          conan remote login products "${{ secrets.USERPRODUCTS }}" -p "${{ secrets.TOKENPRODUCTS }}"
      - name: Download pkglists
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: uploaded_*.json
          merge-multiple: true
      - name: Display structure of downloaded files
          run: ls -R
      - name: promote packages
        run: | 
          conan pkglist merge -l uploaded_windows.json -l uploaded_linux.json --format=json > uploaded.json
          conan download --list=uploaded.json -r=packages --format=json > promote.json
          conan upload --list=promote.json -r=products -c
