name: Windows build

on:
  workflow_call:
    secrets:
      USERDEVELOP:
        required: true
      TOKENDEVELOP:
        required: true
      USERPACKAGES:
        required: true
      TOKENPACKAGES:
        required: true

jobs:
  windows_build:
    runs-on: windows-2022
    name: Build Windows package
    steps:
      - name: Configure environment and install Conan release
        run: python3 -m pip install conan
      - name: Configure repos
        run: |
          conan remote add develop https://conandev.jfrog.io/artifactory/api/conan/citutorial-develop 
          conan remote login develop "${{ secrets.USERDEVELOP }}" -p "${{ secrets.TOKENDEVELOP }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build package
        run: |
          conan profile detect
          conan create . --build="missing:mathlib/*" --format=json > graph.json
      - name: upload package
        run: | 
          conan remote add packages https://conandev.jfrog.io/artifactory/api/conan/citutorial-packages
          conan remote login packages "${{ secrets.USERPACKAGES }}" -p "${{ secrets.TOKENPACKAGES }}"
          conan list --graph=graph.json --graph-binaries=build --format=json > built.json
          conan upload -l=built.json -r=packages -c --format=json > uploaded_release.json
      - name: 'Upload pkglist'
        uses: actions/upload-artifact@v4
        with:
          name: uploaded_windows.json
          path: uploaded_windows.json
